agent:
  gamma: 0.9998
  rar: 1.1
  rar_decay: 0.99999
  memory_size: 150000
  minibatch_size: 512
  replay_freq: 20
  target_update: 125000
  optim_type: torch.optim.adam.Adam
  optim_args: 
    lr: 0.0015
model:
  units: [64, 16] 

# criterion: