agent:
  gamma: 0.99
  rar: 1.00
  rar_decay: 0.995
  memory_size: 1000000
  minibatch_size: 1024
  replay_freq: 5
  target_update: 30000
  optim_type: torch.optim.adadelta.Adadelta
  optim_args:
    lr: 1
  device: cuda

model:
  units: [32, 16]
  memory: LSTM