agent:
  gamma: 0.98
  rar: 1.0
  rar_decay: 0.998
  memory_size: 1000000
  minibatch_size: 256
  replay_freq: 1
  target_update: 5000
  optim_type: torch.optim.adadelta.Adadelta
  optim_args:
    lr: 1
  device: cuda

model:
  units: [128, 32]

# criterion: