agent:
  gamma: 0.99
  rar: 1.0
  rar_decay: 0.996
  memory_size: 1000000
  minibatch_size: 2048
  replay_freq: 10
  target_update: 5000
  optim_type: torch.optim.adam.Adam
  optim_args:
    lr: 0.001
  device: cpu

model:
  units: [32]

# criterion: